language: go

env:
  - GO15VENDOREXPERIMENT=1

go:
  - 1.5
  - 1.6
  - tip

install:
  - go get github.com/apache/thrift/lib/go/thrift
  - go get github.com/elodina/go-avro
  - go get github.com/elodina/siesta
  - go get github.com/elodina/siesta-producer
  - go get github.com/yanzay/log
  - go build -v

script: go test -v ./...
